### ISSUE TITLE
Does not work in strapi 4.6.1

### ISSUE THREAD

**Issue by cervmi** [nicolashmln/strapi-plugin-responsive-image#30]
Installed as instructed. But during `strapi start` it shows error:
`
error: Cannot find module '@strapi/plugin-upload/server/utils/file'
`

Which is true, such file is not there.

**Comment by JWandscheer** [comment]
I think strapi changed the way the file lib is imported (https://github.com/strapi/strapi/commit/53161238013db79cd34505907a10d8c0238643a4).
Importing file using
`require('@strapi/utils/lib/file');` instead of `require("@strapi/plugin-upload/server/utils/file");` should work?

**Comment by nicolashmln** [comment]
Fixed in v1.0.1
