### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl

### ISSUE THREAD

**Issue by Yurgeman** [nicolashmln/strapi-plugin-responsive-image#9]
### Describe the bug

```
yarn run v1.22.10
$ strapi develop
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Users/yura/git/gps/negabarit_teams/strapi/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/yura/git/gps/negabarit_teams/strapi/node_modules/strapi-plugin-responsive-image/node_modules/sharp/build/Release/../../vendor/8.10.0/lib/libvips-cpp.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: /Users/yura/git/gps/negabarit_teams/strapi/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/yura/git/gps/negabarit_teams/strapi/node_modules/strapi-plugin-responsive-image/node_modules/sharp/build/Release/../../vendor/8.10.0/lib/libvips-cpp.42.dylib

✨  Done in 3.48s.
```

### Expected behavior

After upgrade Strapi from 3.5.4 to 3.6.0. And as expected, the `node_modules` folder and the` yarn.lock` file were deleted

```
 strapi                               3.5.4  →   3.6.0     
 strapi-admin                         3.5.4  →   3.6.0     
 strapi-connector-bookshelf           3.5.4  →   3.6.0     
 strapi-plugin-content-manager        3.5.4  →   3.6.0     
 strapi-plugin-content-type-builder   3.5.4  →   3.6.0     
 strapi-plugin-documentation          3.5.4  →   3.6.0     
 strapi-plugin-email                  3.5.4  →   3.6.0     
 strapi-plugin-graphql                3.5.4  →   3.6.0     
 strapi-plugin-sentry                ^3.5.4  →  ^3.6.0     
 strapi-plugin-upload                 3.5.4  →   3.6.0     
 strapi-plugin-users-permissions      3.5.4  →   3.6.0     
 strapi-provider-email-nodemailer    ^3.5.4  →  ^3.6.0     
 strapi-utils                         3.5.4  →   3.6.0  
```
Then `yarn install` & `yarn build --clean` - Ok 
Then `yarn develop` ... and oops, an error popped up

### System

- Node.js version: v14.15.5
- NPM version:6.14.11
- Strapi version:  3.6.0  
- Database: Postgres
- Operating system: macOS Big Sur on Apple MacBook Pro (Apple M1)

**Comment by nicolashmln** [comment]
I saw you've put an issue here as well https://github.com/strapi/strapi/issues/10108 
I have the same bug and no idea why yet. Might be related to strapi and how they use sharp, let's see the responses of your issue.
I'm also on Big Sur but with an Intel processor.

**Comment by cruonline** [comment]
Just so you know, I didn't get this issue on W10 after upgrading. Just issue #10 without any errors.
I will try to replicate this on my Mac. I can test both Catalina and Big Sur. Both Intel.

**Comment by Yurgeman** [comment]
most likely the problem can be solved in 2 ways:
1. Update the sharp dependency to the latest version [2460](https://github.com/lovell/sharp/issues/2460#issuecomment-783401553)
2. installing node js node-v16. 0. 0-darwin-arm64, but strape supports versions up to 14

**Comment by Yurgeman** [comment]
the problem is solved by updating the dependencies.
I made a fork and updated the dependencies - everything worked

```
"sharp": "^0.28.1",
"strapi-plugin-upload": "^3.6.1",
 "strapi-utils": "^3.6.1",
"styled-components": "^5.2.3"
```

**Comment by Yurgeman** [comment]
This does not solve the problem with the left menu [#10](https://github.com/nicolashmln/strapi-plugin-responsive-image/issues/10)

**Comment by nicolashmln** [comment]
Fixed in 0.4
